# Base settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
CELL_SIZE = 20

# Derived settings (calculated here!)
GRID_WIDTH = SCREEN_WIDTH // CELL_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // CELL_SIZE

# Colors of each element
SNAKE_COLOR = (0, 255, 0)
FOOD_COLOR = (255, 0, 0)
BACKGROUND_IMAGE = ('C:ahmad\Downloads\snakegame.jpg')
BACKGROUND_COLOR = (0, 0, 0)
WALL_COLOR = (255, 255, 0)
SCORE_TEXT_COLOR = (0, 255, 0)
GAME_OVER_TEXT_COLOR = (255, 0, 0)
SNAKE_HEAD_COLOR = (0, 0, 255)

# Gameplay
GAME_SPEED = 10

# FONTS
FONT_NAME = None

FONT_SIZE_SCORE = 24
FONT_SIZE_GAMEOVER = 48

#BACKGROUND_COLOR = (0, 0, 0)