
# Base settings
SCREEN_WIDTH = 700
SCREEN_HEIGHT = 500
CELL_SIZE = 20

# Derived settings (calculated here!)
GRID_WIDTH = SCREEN_WIDTH // CELL_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // CELL_SIZE

# Colors of each element
SNAKE_COLOR = (0, 0, 0)
FOOD_COLOR = (255, 0, 0)
RESTART_BACKGROUND_COLOR = (255, 255, 255)
BACKGROUND_IMAGE_MAINSCREEN = ('snakegame.png')
GAME_OVER_SCREEN = ('gameover.jpg')
BACKGROUND_IMAGE_START = ('startscreensnake.jpg')
BACKGROUND_COLOR = (0, 0, 0)
WALL_COLOR = (255, 255, 0)
SCORE_TEXT_COLOR = (0, 0, 0)
GAME_OVER_TEXT_COLOR = (255, 0, 0)
SNAKE_HEAD_COLOR = (0, 0, 255)
BUTTON_TEXT_COLOR = (255, 0, 0)
TITLE_COLOR = (255, 255, 255)

# Gameplay
GAME_SPEED = 10

# FONTS
FONT_NAME = "assets/fonts/PixelifySans-Regular.ttf"

FONT_SIZE_SCORE = 24
FONT_SIZE_GAMEOVER = 48
FONT_HIGH_SCORE = 24
BUTTON_FONT_SIZE = 24
TITLE_FONT_SIZE = 48

#BACKGROUND_COLOR = (0, 0, 0)